### ISSUE TITLE
Mounting hardware? (nightmare)

### ISSUE THREAD

**Issue by quark-works** [cfbender/keyboards#1]
There are no specifications as to which hardware to use with the 3D printed nightmare case. Ordered some PCBs and printed a case but I see no information whatsoever regarding this.

**Comment by quark-works** [comment]
As specified in an email from keyhive:
"You'll need heat set inserts for the plastic and 6mm M2 scres."

**Comment by cfbender** [comment]
Hey @Armastardo sorry I never saw this! Let me know if you have any other questions about the case
