### ISSUE TITLE
Any plans to add Quefrency left w/ macro case files?

### ISSUE THREAD

**Issue by sushantkrishnan** [cfbender/keyboards#13]
I ask this , because apart from the Keebio repo, this is the only open source stacked acrylic case I can find. Since I have no experience with CAD, it would take time for me to make these modifications by myself

**Comment by cfbender** [comment]
Hi @sushantkrishnan! I don't currently have any plans to do so, but it is something I could look into. Can't really speak for a timeline or anything though

**Comment by sushantkrishnan** [comment]
Okay thanks for letting me know.

**Comment by sushantkrishnan** [comment]
@cfbender Tried tinkering with fusion360 but its a bit much for me right now haha. Putting this quefrency project on hold for now I guess.

**Comment by cfbender** [comment]
@sushantkrishnan no worries, I will try to get around to it this weekend! it shouldn't be too hard to do I think.

**Comment by cfbender** [comment]
Hi @sushantkrishnan! Decided to take a crack at this tonight. The files are now added, but untested. I have fairly high confidence in them but I have not tested them personally. Hope this helps!

**Comment by sushantkrishnan** [comment]
Wow! Thanks for doing this, I will definitely be cutting this design out for my build. Will let you know how it goes.
