### ISSUE TITLE
Quefrency feet typing angles/thickness help

### ISSUE THREAD

**Issue by sushantkrishnan** [cfbender/keyboards#15]
For the various feet options included in the case files. What would you recommend the be the ideal thickness, feet configuration and typing angles for the design?

**Comment by cfbender** [comment]
I would probably do the long feet 2 3mm layers (1 F0 and 1 F1). The short/regular feet can also work for the 60%/non-macro halves

**Comment by sushantkrishnan** [comment]
Okay, thanks for the help
