### ISSUE TITLE
[Question] Are there any plans to add the aluminum-corne-helidox-case project files?

### ISSUE THREAD

**Issue by MRTAFU** [cfbender/keyboards#3]
Hi @cfbender ,

I was looking for a case for my Corne Cherry and found a beautiful one, which was the IMK Corne case.
But unfortunately, I didn't make it for the Group Buy at any region.
So instead, I was thinking of ordering a local machinery factory to make me one 😄 
It'll be nice if I could use the original blue print to order it.

Would there be any plans for adding the aluminum-corne-helidox-case project files to this repo?
Hope there aren't any contract restrictions which refrains public availability...

Ref) https://keyhive.xyz/shop/aluminum-corne-helidox-case

Many Thanks!!!

**Comment by cfbender** [comment]
Hi there!

Unfortunately - I was not the designer of the IMK corne case, so I don't have access to those files. I would be willing to export the 3D printed case as a STEP file if that would be helpful as a starting point though!

**Comment by MRTAFU** [comment]
Thanks for the reply!
Oh, my bad. The design looked so similar, i was assuming you were the same person🙏
Your suggestion would really help!!
Would it be possible?

**Comment by cfbender** [comment]
No worries! I think there's just not a ton you can do with the case design for something so small and unique.

I just pushed https://github.com/cfbender/keyboards/commit/01bc5617503332a80aa1b9248cf6e5ac71e0bebb which should contain everything you'd need! I'll go ahead and close this issue for now - let me know if I can help any further!
